// STYLES
import styles from "../styles/Home.module.scss";
// NEXT COMPONENTS
import Head from "next/head";
import Image from "next/image";
// CUSTOM COMPONENTS
import Button from "../components/layout/smallComponents/button/Button";
import WhiteSpace from "../components/layout/whiteSpace/whiteSpace";
// IMAGE SOURCES
import codeThinkigSrc from "../public/codeThinking.svg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.introSection}>
          <div className={styles.introSectionTextWrapper}>
            <h1>Dwave Code</h1>
            <h2>Besplatna škola programiranja</h2>
            <p>
              Na našem sajtu naučićete sve od osnova do naprednih tehnologija
              koje se koriste za programiranje web stranica. Takođe naučićete da
              razmišljate kao programer i da rešavate realne probleme.
            </p>
            <Button text={"Počni sa učenjem"} link="/blog/html" />
          </div>
          <div className={styles.introSectionImageWrapper}>
            <Image src={codeThinkigSrc} alt="Code Thinking" />
          </div>
        </section>
        <WhiteSpace />
      </main>
    </div>
  );
}
